### ISSUE TITLE
Setting: add trailing slashes

### ISSUE THREAD

**Issue by robdekort** [nextbuzz/buzz-seo#45]
It would be nice if you can add a trailing slash to all (perma)links requested to prevent 301 redirects and keep pagerank.

**Comment by lengthofrope** [comment]
Can you explain this a little further :)

**Comment by robdekort** [comment]
Sorry, was in a hurry. I might be wrong, but in some cases Wordpress doesn't return a local url / permalink with a trailing slash. In other cases users might forget to add a trailing slash as they don't care and shouldn't care. When Wordpress loads a page without a trailing slash in the URL it will 301 to the correct page with the trailing slash. And this is bad for SEO. Perhaps Buzz SEO could interfere somewhere by adding a trailing slash when it's not available.

**Comment by lengthofrope** [comment]
Ok, I've tested this some more. It seems WordPress automagicly redirects pages without a trailingslash to the version with trailingslash. So there should be no issue here. Just in case I will add an addiotional check by using the trailingslashit functions to make sure our plugin also acts this way. As far as I know this is never used because WordPress is already handling this, but it is a nice addition nevertheless. Better be safe than sorry :)

**Comment by lengthofrope** [comment]
Ok, there is another issue at large here. WordPress tries to redirect to another simularly named slug before given a 404. Which prevails the plugin from using our redirects. So we need to change the way the redirections are handled.
